export const SET_GET_POKEMONS = "SET_GET_POKEMONS";
export const SUCCESS_GET_POKEMON = "SUCCESS_GET_POKEMON";
export const ERROR_GET_POKEMONS = "ERROR_GET_POKEMONS";
export const ADD_POKEMON = "ADD_POKEMON";
export const SET_OPEN_MODAL = "SET_OPEN_MODAL";
export const CLEAN_CART = "CLEAN_CART";
export const BACK_DASHBOARD = "BACK_DASHBOARD";
export const SET_REMOVE_POKEMON = "SET_REMOVE_POKEMON";
export const SET_GET_POKEDEX = "SET_GET_POKEDEX";
export const POKEMON_DETAIL = "POKEMON_DETAIL";




